### ISSUE TITLE
does this protect app from reverse-engineered

### ISSUE THREAD

**Issue by tbswork1** [SerialKeyManager/SKM-Client-API-CPP#16]
What if cracker reverse-engineers the app and shortcut to code of license check?

**Comment by artemlos** [comment]
@tbswork1 thanks for the question. Since the SDK is included as a part of a project, it does not on its own provide a way to obfuscate the code. To prevent an adversary from reverse engineering the application, an obfuscation software can be used. This will make it harder, but not impossible, for an adversary to reverse engineer the application. For critical code, it's better to never let it execute on the client machine and instead expose it as an API endpoint.
